### ISSUE TITLE
您好好，请问下原始的顶点出入度 和顶点嵌入是怎么生成的呀?我的方向与您类似，希望得到您的一些帮助，谢谢.

### ISSUE THREAD

**Issue by mosquitosun** [MrYansong/CCasGNN#3]

**Comment by MrYansong** [comment]
原始顶点出入度都是数据集里面的信息，作为顶点特征输入到GNN中，通过GNN得到顶点嵌入。

**Comment by mosquitosun** [comment]
首先谢谢您的解答。您好，我的意思是指比如说in_degree: {'729916': -0.7825409800982147, '672995': 0.9720531242241086, '1725333': 1.888868061617755, '1465972': -0.7577011665235099, '649806': -0.5228520199990291, '330932': -0.6199531094274202, '838742': -0.9654523346028584, '461222': -0.18864361917572944, }
# location_embedding: {'729916': [0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0], '672995': [0.8414709848078965, 0.5403023058681398, 0.4093089240419384, 0.9123958596462561, 0.17689218624615002, 0.9842302344700946, 0.07491915794147602, 0.9971896107427816, 0.03161750640243371, 0.9995000416652778, 0.01333481909619642, 0.999911087347106, 0.005623383613960186, 0.9999841886533658, 0.0023713714831265597, 0.9999971882946916], '1725333': [0.9092974268256817, 
# nodes_embedding: {'729916': [-0.5609350176498449, 2.7684516544981386, -0.7406406327050062, 3.4409337030916354, -0.9225203259426284, 0.4879500364742666, 0.89}这里面的数据是如何得到的？期待您的解惑，谢谢。

**Comment by MrYansong** [comment]
这个是做了标准化以后的数据。

**Comment by MrYansong** [comment]
这是在原始数据基础上，做了标准化以后的数据。

**Comment by mosquitosun** [comment]
哦哦哦，好的。谢谢您的解答。祝您工作顺利~

**Comment by mosquitosun** [comment]
您好，打扰了，感谢您的耐心回答。我在试验了几天后，还是不能得到数据集提供的location_embbedding和node_embedding是如何得到的，请问可以分享下预处理的源代码吗?我的邮箱是sun255138@163.com。感激不尽，最后祝您科研顺利，工作愉快！
